drop schema ims;
CREATE SCHEMA IF NOT EXISTS `ims`;
USE `ims` ;
CREATE TABLE IF NOT EXISTS `ims`.`customers` (
    `CID` INT(11) NOT NULL AUTO_INCREMENT,
    `first_name` VARCHAR(32) NULL DEFAULT NULL,
    `last_name` VARCHAR(32) NULL DEFAULT NULL,
    PRIMARY KEY (`CID`)
);
CREATE TABLE IF NOT EXISTS `ims`.`item` (
    `IID` INT(11) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(32) NULL DEFAULT NULL,
    `version` DECIMAL(8,2) NULL DEFAULT NULL,
    `price` DECIMAL(8,2) NULL DEFAULT NULL,
    `description` VARCHAR(128) NULL DEFAULT NULL,
    PRIMARY KEY (`IID`)
);

CREATE TABLE IF NOT EXISTS `ims`.`orders` (
    `OID` INT(11) NOT NULL AUTO_INCREMENT,
    `CID` INT(11) NULL DEFAULT NULL,
    PRIMARY KEY (`OID`)
);
CREATE TABLE IF NOT EXISTS `ims`.`item_orders` (
    `OID` INT(11) NOT NULL,
    `IID` INT(11) NOT NULL
);
